-- ===================================================================
-- Life Care Specialty Hospital, Bhatkal — Database Schema + Seed Data
-- GENERATED by tools/build_sql.php from includes/seed_data.php.
-- Do not edit by hand — edit seed_data.php and re-run the generator.
-- Import: phpMyAdmin → your database → Import → choose this file.
-- Generated: 2026-09-07 10:57
-- ===================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET time_zone = '+05:30';

DROP TABLE IF EXISTS `admins`;
CREATE TABLE `admins` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL,
  `email` VARCHAR(160) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `name` VARCHAR(120) NOT NULL DEFAULT '',
  `role` VARCHAR(30) NOT NULL DEFAULT 'admin',
  `failed_attempts` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `locked_until` DATETIME NULL DEFAULT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `admins` (`username`, `email`, `password_hash`, `name`, `role`) VALUES
  ('admin', 'info@lifecarebhatkal.com', '$2y$12$o1zr32Op0ZqyaF0b05iE8u1oKnjSIdpYoYUOytIWvJ2OBcPHwo.3C', 'Hospital Administrator', 'admin');

-- Default admin login → username: admin  |  password: lifecare@admin
-- IMPORTANT: log in and change this password immediately.

DROP TABLE IF EXISTS `site_settings`;
CREATE TABLE `site_settings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `setting_key` VARCHAR(80) NOT NULL,
  `setting_value` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_key` (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `site_settings` (`setting_key`, `setting_value`) VALUES
  ('site_name', 'Life Care Specialty Hospital'),
  ('tagline', 'Keeping you well.'),
  ('email', 'info@lifecarebhatkal.com'),
  ('phone1', '+91 8385992233'),
  ('phone2', '08385 227997'),
  ('whatsapp', '8385992233'),
  ('address', 'Nawayath Colony, Jali Road, Bhatkal 581320, Uttara Kannada Dist., Karnataka'),
  ('address_short', 'Nawayath Colony, Jali Road, Bhatkal 581320'),
  ('opd_hours', '9:00 AM – 1:30 PM & 4:00 PM – 7:30 PM'),
  ('visiting_hours', '11:00 AM – 12:30 PM & 5:00 PM – 8:00 PM'),
  ('pharmacy_hours', '24×7, all days'),
  ('emergency_line', '24×7 Accident & Emergency'),
  ('map_embed', 'https://www.google.com/maps?q=Life+Care+Specialty+Hospital+Bhatkal&output=embed'),
  ('facebook', '#'),
  ('instagram', '#'),
  ('youtube', '#'),
  ('footer_about', 'Life Care Specialty Hospital — bringing modern health facilities to Bhatkal and its surroundings.'),
  ('copyright', '© 2020–2025 Life Care Specialty Hospital, Bhatkal. All Rights Reserved.'),
  ('logo', 'assets/images/brand/logo.png'),
  ('logo_white', 'assets/images/brand/logo-white.png'),
  ('established_year', '2020'),
  ('stat_years', '5+'),
  ('stat_years_label', 'Years of Service'),
  ('stat_patients', '50,000+'),
  ('stat_patients_label', 'Patients Cared For'),
  ('stat_beds', '50'),
  ('stat_beds_label', 'In-patient Beds'),
  ('stat_doctors', '13'),
  ('stat_doctors_label', 'Doctors & Specialists'),
  ('stat_surgeries', '5,000+'),
  ('stat_surgeries_label', 'Successful Surgeries'),
  ('stat_slice', '32'),
  ('stat_slice_label', 'Slice CT Scanner');

DROP TABLE IF EXISTS `departments`;
CREATE TABLE `departments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(160) NOT NULL,
  `slug` VARCHAR(160) NOT NULL,
  `category` VARCHAR(20) NOT NULL DEFAULT 'opd',
  `thumb_image` VARCHAR(255) NULL,
  `hero_image` VARCHAR(255) NULL,
  `short_desc` TEXT NULL,
  `overview` MEDIUMTEXT NULL,
  `services` TEXT NULL,
  `seo_title` VARCHAR(200) NULL,
  `meta_description` VARCHAR(300) NULL,
  `display_order` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'published',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_slug` (`slug`),
  KEY `idx_cat` (`category`), KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `departments` (`id`, `name`, `slug`, `category`, `thumb_image`, `hero_image`, `short_desc`, `overview`, `services`, `seo_title`, `meta_description`, `display_order`, `status`) VALUES
  (1, 'General Medicine', 'general-medicine', 'opd', 'assets/images/facilities/daycare.jpg', 'assets/images/facilities/daycare.jpg', 'Comprehensive diagnosis and treatment of adult illnesses — from fever, infections and lifestyle disorders to chronic disease management.', '<p>Comprehensive diagnosis and treatment of adult illnesses — from fever, infections and lifestyle disorders to chronic disease management.</p><p>At Life Care Specialty Hospital, our general medicine care is delivered with modern diagnostics, experienced clinicians and a focus on accessible, affordable treatment — so residents of Bhatkal and its surroundings receive quality care close to home.</p>', 'General consultation & health check-ups
Management of diabetes, hypertension & thyroid
Infectious & seasonal illnesses
Respiratory & gastrointestinal care
Preventive health screening', 'General Medicine in Bhatkal | Life Care Specialty Hospital', 'Comprehensive diagnosis and treatment of adult illnesses — from fever, infections and lifestyle disorders to chronic disease management.', 1, 'published'),
  (2, 'Gynaecology & Obstetrics', 'gynaecology-obstetrics', 'opd', 'assets/images/facilities/ot.jpg', 'assets/images/facilities/ot.jpg', 'Complete women\'s health care — antenatal care, safe deliveries in our modern labour theatre, and treatment of gynaecological conditions.', '<p>Complete women\'s health care — antenatal care, safe deliveries in our modern labour theatre, and treatment of gynaecological conditions.</p><p>At Life Care Specialty Hospital, our gynaecology & obstetrics care is delivered with modern diagnostics, experienced clinicians and a focus on accessible, affordable treatment — so residents of Bhatkal and its surroundings receive quality care close to home.</p>', 'Antenatal & postnatal care
Normal & assisted deliveries
Anomaly & pregnancy ultrasound scanning
Gynaec surgeries
Menstrual & menopausal care', 'Gynaecology & Obstetrics in Bhatkal | Life Care Specialty Hospital', 'Complete women\'s health care — antenatal care, safe deliveries in our modern labour theatre, and treatment of gynaecological conditions.', 2, 'published'),
  (3, 'Orthopaedics', 'orthopaedics', 'opd', 'assets/images/facilities/ot-2.jpg', 'assets/images/facilities/ot-2.jpg', 'Expert care for bones, joints and the musculoskeletal system, including joint replacement and trauma surgery, supported by digital X-ray and CT.', '<p>Expert care for bones, joints and the musculoskeletal system, including joint replacement and trauma surgery, supported by digital X-ray and CT.</p><p>At Life Care Specialty Hospital, our orthopaedics care is delivered with modern diagnostics, experienced clinicians and a focus on accessible, affordable treatment — so residents of Bhatkal and its surroundings receive quality care close to home.</p>', 'Fracture & trauma management
Total knee & hip replacement
Arthroscopy & sports injuries
Spine & joint pain treatment
Post-operative physiotherapy', 'Orthopaedics in Bhatkal | Life Care Specialty Hospital', 'Expert care for bones, joints and the musculoskeletal system, including joint replacement and trauma surgery, supported by digital X-ray and CT.', 3, 'published'),
  (4, 'General & Laparoscopic Surgery', 'general-laparoscopic-surgery', 'opd', 'assets/images/facilities/laparoscopy.jpg', 'assets/images/facilities/laparoscopy.jpg', 'Bhatkal\'s first full-time laparoscopy service — minimally invasive keyhole surgery with faster recovery and smaller scars.', '<p>Bhatkal\'s first full-time laparoscopy service — minimally invasive keyhole surgery with faster recovery and smaller scars.</p><p>At Life Care Specialty Hospital, our general & laparoscopic surgery care is delivered with modern diagnostics, experienced clinicians and a focus on accessible, affordable treatment — so residents of Bhatkal and its surroundings receive quality care close to home.</p>', 'Laparoscopic (keyhole) surgery
General & onco-surgery
Colonoscopy & endoscopy
Hernia, gallbladder & appendix surgery
Day-care surgical procedures', 'General & Laparoscopic Surgery in Bhatkal | Life Care Specialty Hospital', 'Bhatkal\'s first full-time laparoscopy service — minimally invasive keyhole surgery with faster recovery and smaller scars.', 4, 'published'),
  (5, 'Dental — Oral & Maxillofacial', 'dental', 'opd', 'assets/images/about/about-1.jpg', 'assets/images/about/about-1.jpg', 'Complete dental and oral-maxillofacial care led by experienced surgeons — from routine dentistry to complex facial surgery.', '<p>Complete dental and oral-maxillofacial care led by experienced surgeons — from routine dentistry to complex facial surgery.</p><p>At Life Care Specialty Hospital, our dental — oral & maxillofacial care is delivered with modern diagnostics, experienced clinicians and a focus on accessible, affordable treatment — so residents of Bhatkal and its surroundings receive quality care close to home.</p>', 'Dental check-ups, fillings & extractions
Root canal & crowns
Oral & maxillofacial surgery
Orthodontics & cosmetic dentistry
Paediatric dental care', 'Dental — Oral & Maxillofacial in Bhatkal | Life Care Specialty Hospital', 'Complete dental and oral-maxillofacial care led by experienced surgeons — from routine dentistry to complex facial surgery.', 5, 'published'),
  (6, 'Physiotherapy', 'physiotherapy', 'opd', 'assets/images/facilities/physiotherapy.jpg', 'assets/images/facilities/physiotherapy.jpg', 'A specialised physiotherapy unit for pain relief, rehabilitation and recovery — for joints, spine, sports injuries and neurological conditions.', '<p>A specialised physiotherapy unit for pain relief, rehabilitation and recovery — for joints, spine, sports injuries and neurological conditions.</p><p>At Life Care Specialty Hospital, our physiotherapy care is delivered with modern diagnostics, experienced clinicians and a focus on accessible, affordable treatment — so residents of Bhatkal and its surroundings receive quality care close to home.</p>', 'Joint, knee, back & neck pain
Sports injury rehabilitation
Spondylosis & post-surgical recovery
Stroke & paralysis rehabilitation
Care for cerebral palsy & Parkinson\'s', 'Physiotherapy in Bhatkal | Life Care Specialty Hospital', 'A specialised physiotherapy unit for pain relief, rehabilitation and recovery — for joints, spine, sports injuries and neurological conditions.', 6, 'published'),
  (7, 'Cardiology', 'cardiology', 'visiting', 'assets/images/facilities/ultrasound.jpg', 'assets/images/facilities/ultrasound.jpg', 'Visiting cardiology consultation supported by in-house ECG, ECHO and TMT for the diagnosis and management of heart conditions.', '<p>Visiting cardiology consultation supported by in-house ECG, ECHO and TMT for the diagnosis and management of heart conditions.</p><p>At Life Care Specialty Hospital, our cardiology care is delivered with modern diagnostics, experienced clinicians and a focus on accessible, affordable treatment — so residents of Bhatkal and its surroundings receive quality care close to home.</p>', 'Cardiac consultation (visiting)
ECG, ECHO & TMT — 24×7
Hypertension & heart-failure care
Cardiac risk assessment
Follow-up & medication management', 'Cardiology in Bhatkal | Life Care Specialty Hospital', 'Visiting cardiology consultation supported by in-house ECG, ECHO and TMT for the diagnosis and management of heart conditions.', 7, 'published'),
  (8, 'Neurology', 'neurology', 'visiting', 'assets/images/facilities/ct-scan.jpg', 'assets/images/facilities/ct-scan.jpg', 'Visiting neurology services for disorders of the brain, spine and nervous system, backed by 32-slice CT imaging.', '<p>Visiting neurology services for disorders of the brain, spine and nervous system, backed by 32-slice CT imaging.</p><p>At Life Care Specialty Hospital, our neurology care is delivered with modern diagnostics, experienced clinicians and a focus on accessible, affordable treatment — so residents of Bhatkal and its surroundings receive quality care close to home.</p>', 'Neurology consultation (visiting)
Stroke evaluation & follow-up
Headache, epilepsy & seizure care
Nerve & spine disorder assessment
CT-supported diagnosis', 'Neurology in Bhatkal | Life Care Specialty Hospital', 'Visiting neurology services for disorders of the brain, spine and nervous system, backed by 32-slice CT imaging.', 8, 'published'),
  (9, 'Dermatology', 'dermatology', 'visiting', 'assets/images/about/stethoscope.jpg', 'assets/images/about/stethoscope.jpg', 'Visiting dermatology care for skin, hair and nail conditions — medical and cosmetic.', '<p>Visiting dermatology care for skin, hair and nail conditions — medical and cosmetic.</p><p>At Life Care Specialty Hospital, our dermatology care is delivered with modern diagnostics, experienced clinicians and a focus on accessible, affordable treatment — so residents of Bhatkal and its surroundings receive quality care close to home.</p>', 'Dermatology consultation (visiting)
Acne, allergy & infection treatment
Skin & hair disorder care
Cosmetic dermatology
Chronic skin condition management', 'Dermatology in Bhatkal | Life Care Specialty Hospital', 'Visiting dermatology care for skin, hair and nail conditions — medical and cosmetic.', 9, 'published'),
  (10, 'Psychiatry', 'psychiatry', 'visiting', 'assets/images/about/vision.jpg', 'assets/images/about/vision.jpg', 'Visiting psychiatry services offering compassionate, confidential mental-health care for individuals and families.', '<p>Visiting psychiatry services offering compassionate, confidential mental-health care for individuals and families.</p><p>At Life Care Specialty Hospital, our psychiatry care is delivered with modern diagnostics, experienced clinicians and a focus on accessible, affordable treatment — so residents of Bhatkal and its surroundings receive quality care close to home.</p>', 'Psychiatry consultation (visiting)
Anxiety, depression & stress care
Sleep & mood disorders
Counselling & follow-up
De-addiction guidance', 'Psychiatry in Bhatkal | Life Care Specialty Hospital', 'Visiting psychiatry services offering compassionate, confidential mental-health care for individuals and families.', 10, 'published'),
  (11, 'Diabetology & Endocrinology', 'diabetology-endocrinology', 'visiting', 'assets/images/facilities/lab.jpg', 'assets/images/facilities/lab.jpg', 'Visiting diabetology and endocrinology care for diabetes, thyroid and hormonal disorders, supported by our hi-tech laboratory.', '<p>Visiting diabetology and endocrinology care for diabetes, thyroid and hormonal disorders, supported by our hi-tech laboratory.</p><p>At Life Care Specialty Hospital, our diabetology & endocrinology care is delivered with modern diagnostics, experienced clinicians and a focus on accessible, affordable treatment — so residents of Bhatkal and its surroundings receive quality care close to home.</p>', 'Diabetes & endocrine consultation (visiting)
Thyroid & hormonal disorder care
Diabetic foot & complication screening
Lab-supported monitoring
Diet & lifestyle guidance', 'Diabetology & Endocrinology in Bhatkal | Life Care Specialty Hospital', 'Visiting diabetology and endocrinology care for diabetes, thyroid and hormonal disorders, supported by our hi-tech laboratory.', 11, 'published'),
  (12, 'Pulmonology', 'pulmonology', 'visiting', 'assets/images/facilities/xray.jpg', 'assets/images/facilities/xray.jpg', 'Visiting pulmonology services for respiratory and lung conditions, supported by digital X-ray and HRCT thorax imaging.', '<p>Visiting pulmonology services for respiratory and lung conditions, supported by digital X-ray and HRCT thorax imaging.</p><p>At Life Care Specialty Hospital, our pulmonology care is delivered with modern diagnostics, experienced clinicians and a focus on accessible, affordable treatment — so residents of Bhatkal and its surroundings receive quality care close to home.</p>', 'Pulmonology consultation (visiting)
Asthma & COPD management
Respiratory infection care
HRCT thorax & digital X-ray
Breathing & lung-function assessment', 'Pulmonology in Bhatkal | Life Care Specialty Hospital', 'Visiting pulmonology services for respiratory and lung conditions, supported by digital X-ray and HRCT thorax imaging.', 12, 'published');

DROP TABLE IF EXISTS `doctors`;
CREATE TABLE `doctors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(160) NOT NULL,
  `doctor_type` VARCHAR(20) NOT NULL DEFAULT 'resident',
  `department` VARCHAR(160) NULL,
  `qualification` VARCHAR(200) NULL,
  `designation` VARCHAR(200) NULL,
  `image` VARCHAR(255) NULL,
  `available_days` VARCHAR(120) NULL,
  `available_time` VARCHAR(160) NULL,
  `base_city` VARCHAR(200) NULL,
  `short_bio` TEXT NULL,
  `full_bio` MEDIUMTEXT NULL,
  `display_order` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'published',
  PRIMARY KEY (`id`),
  KEY `idx_type` (`doctor_type`), KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `doctors` (`id`, `name`, `doctor_type`, `department`, `qualification`, `designation`, `image`, `available_days`, `available_time`, `base_city`, `short_bio`, `full_bio`, `display_order`, `status`) VALUES
  (1, 'Dr. Mohammad Yasin (Saudagar)', 'resident', 'Dental — Oral & Maxillofacial', 'BDS, MDS, FAM (Germany)', 'Consultant Dental & Maxillofacial Surgeon', 'assets/images/doctors/dr-mohammad-yasin.jpg', 'Mon – Sat', '9:00 AM – 1:30 PM & 4:00 PM – 7:30 PM', '', 'Consultant dental and oral & maxillofacial surgeon with advanced fellowship training in Germany.', '<p>Dr. Mohammad Yasin leads the dental and oral & maxillofacial services at Life Care Specialty Hospital, bringing advanced training including a fellowship in Germany. He handles routine dentistry through to complex maxillofacial surgery.</p>', 1, 'published'),
  (2, 'Dr. Kenneth Crispin', 'resident', 'Physician / Diabetology', 'MBBS, MD', 'Consultant Physician & Diabetologist', 'assets/images/doctors/dr-kenneth-crispin.png', 'Mon – Sat', '9:00 AM – 1:30 PM & 4:00 PM – 7:30 PM', '', 'Consultant physician and diabetologist managing adult medicine, diabetes and chronic disease.', '<p>Dr. Kenneth Crispin provides comprehensive internal medicine and diabetology care, from acute illness to long-term management of diabetes, hypertension and lifestyle disorders.</p>', 2, 'published'),
  (3, 'Dr. Mohammed Nawab', 'resident', 'Orthopaedics', 'MBBS, MS', 'Consultant Orthopaedic Surgeon', 'assets/images/doctors/dr-mohammed-nawab.png', 'Mon – Sat', '9:00 AM – 1:30 PM & 4:00 PM – 7:30 PM', '', 'Consultant orthopaedic surgeon specialising in trauma, joint replacement and sports injuries.', '<p>Dr. Mohammed Nawab handles the full range of orthopaedic care — fracture and trauma management, joint replacement, arthroscopy and treatment of chronic joint and spine pain, supported by digital X-ray and CT.</p>', 3, 'published'),
  (4, 'Dr. Mohammed Naushad', 'resident', 'Radiology', 'MBBS, MD', 'Consultant Radiologist', 'assets/images/doctors/dr-mohammed-naushad.png', 'Mon – Sat', '24×7 (on call)', '', 'In-house full-time radiologist performing ultrasound, CT and diagnostic imaging.', '<p>Dr. Mohammed Naushad is our full-time in-house radiologist, performing ultrasound, colour Doppler, 32-slice CT and a wide range of scans, providing accurate reports round the clock.</p>', 4, 'published'),
  (5, 'Dr. Shravya Acharya', 'resident', 'Dental', 'BDS', 'Dental Surgeon', 'assets/images/doctors/placeholder.svg', 'Mon – Sat', '9:00 AM – 1:30 PM & 4:00 PM – 7:30 PM', '', 'Dental surgeon providing routine and preventive dental care.', '<p>Dr. Shravya Acharya provides general and preventive dentistry as part of the Life Care dental team.</p>', 5, 'published'),
  (6, 'Dr. Riyaz Husain Kashralli', 'resident', 'Casualty / Emergency', 'MBBS', 'Emergency Medical Officer', 'assets/images/doctors/placeholder.svg', 'Every day (rotational)', '24×7', '', 'Emergency medical officer for the 24×7 accident & emergency department.', '<p>Dr. Riyaz Husain Kashralli is part of the duty-doctor team staffing our 24×7 Accident & Emergency department.</p>', 6, 'published'),
  (7, 'Dr. Dheeraj Shetty', 'resident', 'Casualty / Emergency', 'MBBS', 'Emergency Medical Officer', 'assets/images/doctors/placeholder.svg', 'Every day (rotational)', '24×7', '', 'Emergency medical officer for the 24×7 accident & emergency department.', '<p>Dr. Dheeraj Shetty is part of the duty-doctor team staffing our 24×7 Accident & Emergency department.</p>', 7, 'published'),
  (8, 'Dr. El Roy Saldanha', 'resident', 'Onco & General Surgery', 'MBBS, MS', 'Consultant Onco & General Surgeon', 'assets/images/doctors/placeholder.svg', 'By appointment', 'Contact reception', '', 'Consultant surgeon for general and onco-surgical care.', '<p>Dr. El Roy Saldanha provides general and onco-surgical care, including laparoscopic procedures, at Life Care Specialty Hospital.</p>', 8, 'published'),
  (9, 'Ms. Ashwini Shetty', 'support', 'Physiotherapy', 'BPT', 'Physiotherapist', 'assets/images/doctors/ms-ashwini-shetty.png', 'Mon – Sat', '9:00 AM – 1:30 PM & 4:00 PM – 7:30 PM', '', 'Physiotherapist in the specialised physiotherapy & rehabilitation unit.', '<p>Ms. Ashwini Shetty is a qualified physiotherapist supporting pain relief, rehabilitation and post-surgical recovery.</p>', 9, 'published'),
  (10, 'Dr. Afra Maqiyah', 'support', 'Physiotherapy', 'BPT, MIAP', 'Physiotherapist', 'assets/images/doctors/placeholder.svg', 'Mon – Sat', '9:00 AM – 1:30 PM & 4:00 PM – 7:30 PM', '', 'Physiotherapist in the specialised physiotherapy & rehabilitation unit.', '<p>Dr. Afra Maqiyah is a qualified physiotherapist providing rehabilitation and physiotherapy care.</p>', 10, 'published'),
  (11, 'Dr. Narasimha Pai', 'visiting', 'Cardiology', 'MBBS, MD, DM, DNB', 'Visiting Cardiologist', 'assets/images/doctors/dr-narasimha-pai.png', 'Visiting — contact reception', 'By schedule', 'Base city / hospital — to be confirmed', 'Visiting cardiologist supported by in-house ECG, ECHO and TMT.', '<p>Dr. Narasimha Pai visits Life Care Specialty Hospital for cardiology consultation, supported by 24×7 ECG, ECHO and TMT facilities.</p>', 1, 'published'),
  (12, 'Dr. Raghavendra', 'visiting', 'Neurology', 'MBBS, MD, DM', 'Visiting Neurologist', 'assets/images/doctors/dr-raghavendra.png', 'Visiting — contact reception', 'By schedule', 'Base city / hospital — to be confirmed', 'Visiting neurologist for brain, spine and nervous-system disorders.', '<p>Dr. Raghavendra visits Life Care Specialty Hospital for neurology consultation, backed by 32-slice CT imaging.</p>', 2, 'published'),
  (13, 'Dr. Mahima Acharya', 'visiting', 'Psychiatry', 'MBBS, MD', 'Visiting Psychiatrist', 'assets/images/doctors/dr-mahima-acharya.png', 'Visiting — contact reception', 'By schedule', 'Base city / hospital — to be confirmed', 'Visiting psychiatrist offering confidential mental-health care.', '<p>Dr. Mahima Acharya visits Life Care Specialty Hospital for psychiatry consultation, offering compassionate and confidential mental-health care.</p>', 3, 'published');

DROP TABLE IF EXISTS `testimonials`;
CREATE TABLE `testimonials` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `location` VARCHAR(120) NULL,
  `quote` TEXT NOT NULL,
  `rating` TINYINT NOT NULL DEFAULT 5,
  `display_order` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'published',
  PRIMARY KEY (`id`), KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `testimonials` (`id`, `name`, `location`, `quote`, `rating`, `display_order`, `status`) VALUES
  (1, 'Mohammed', 'Bhatkal', 'Impressed with the hospital standards and the wonderful attention from the staff.', 5, 1, 'published'),
  (2, 'Ameena', 'Bhatkal', 'I had a total knee replacement here — it was a great experience from start to finish.', 5, 2, 'published'),
  (3, 'Ganesh', 'Bhatkal', 'Thank you to the whole team. Life Care is very special for us.', 5, 3, 'published'),
  (4, 'Mubeen', 'Bhatkal', 'Excellent treatment and care, with seamless coordination between departments.', 5, 4, 'published'),
  (5, 'Ahmed', 'Bhatkal', 'The staff\'s treatment of patients is remarkable and truly worthy of appreciation.', 5, 5, 'published');

DROP TABLE IF EXISTS `faqs`;
CREATE TABLE `faqs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(300) NOT NULL,
  `answer` TEXT NOT NULL,
  `display_order` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'published',
  PRIMARY KEY (`id`), KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `faqs` (`id`, `question`, `answer`, `display_order`, `status`) VALUES
  (1, 'What are the hospital and OPD timings?', 'OPD consultation hours are 9:00 AM – 1:30 PM and 4:00 PM – 7:30 PM. Duty doctors are available 24×7 every day, and the Accident & Emergency department is open round the clock.', 1, 'published'),
  (2, 'Where is Life Care Specialty Hospital located?', 'We are at Nawayath Colony, Jali Road, Bhatkal 581320, Uttara Kannada District, Karnataka. You will find a Google Map with directions on our Contact page and in the footer.', 2, 'published'),
  (3, 'What are the pharmacy and laboratory timings?', 'Our in-house pharmacy and hi-tech laboratory operate 24×7, all days of the week.', 3, 'published'),
  (4, 'How many visitors are allowed for an in-patient?', 'Two visitors are allowed at a time. For the safety of patients, we request you avoid bringing young children or elderly visitors. Visiting hours are 11:00 AM – 12:30 PM and 5:00 PM – 8:00 PM.', 4, 'published'),
  (5, 'Is a deposit required for admission?', 'Yes. At the time of admission, a deposit of 50% of the estimated cost is collected.', 5, 'published'),
  (6, 'What modes of payment are accepted?', 'We accept Cash, e-Wallet and Online payments. Cheques are not accepted.', 6, 'published');

DROP TABLE IF EXISTS `blog_posts`;
CREATE TABLE `blog_posts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(240) NOT NULL,
  `slug` VARCHAR(240) NOT NULL,
  `category` VARCHAR(80) NULL,
  `author` VARCHAR(160) NULL,
  `publish_date` DATE NULL,
  `featured_image` VARCHAR(255) NULL,
  `excerpt` TEXT NULL,
  `content` MEDIUMTEXT NULL,
  `seo_title` VARCHAR(240) NULL,
  `meta_description` VARCHAR(300) NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'published',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_slug` (`slug`),
  KEY `idx_status` (`status`), KEY `idx_date` (`publish_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `blog_posts` (`id`, `title`, `slug`, `category`, `author`, `publish_date`, `featured_image`, `excerpt`, `content`, `seo_title`, `meta_description`, `status`) VALUES
  (1, 'COVID-19: Understanding the New Strain', 'covid-19-new-strain', 'Medical Updates', 'Dr. Saad Mohammed Athanikar', '2021-01-05', 'assets/images/about/stethoscope.jpg', 'What a new variant means for you and your family, and the simple precautions that continue to protect our community.', '<p>As the COVID-19 virus evolves, new strains emerge that can spread more easily. While this can sound alarming, the fundamentals of protection remain the same.</p><p>Continue to practise good hand hygiene, wear a mask in crowded indoor settings when you are unwell, and keep your vaccinations up to date. If you develop fever, cough or breathing difficulty, seek medical advice early rather than waiting.</p><p>Our 24×7 Accident & Emergency and diagnostic services remain available for anyone who needs assessment. This article is for general awareness and is not a substitute for professional medical advice.</p>', 'Understanding the New COVID-19 Strain | Life Care Bhatkal', 'General awareness on new COVID-19 variants and everyday precautions, from Life Care Specialty Hospital, Bhatkal.', 'published'),
  (2, 'Diabetes: An Insight', 'diabetes-an-insight', 'Health', 'Dr. Saad Mohammed Athanikar', '2020-11-14', 'assets/images/facilities/lab.jpg', 'Diabetes is manageable with the right care. Here is what everyone in Bhatkal should know about prevention and control.', '<p>Diabetes is one of the most common lifestyle conditions today, yet it is highly manageable with early detection and consistent care.</p><p>Simple steps make a real difference: a balanced diet, regular physical activity, maintaining a healthy weight, and routine blood-sugar monitoring. Our hi-tech laboratory and diabetology care make regular monitoring convenient close to home.</p><p>If you have a family history of diabetes or notice symptoms such as increased thirst, frequent urination or fatigue, speak to a physician. This article is for general awareness and is not a substitute for professional medical advice.</p>', 'Diabetes: An Insight | Life Care Specialty Hospital Bhatkal', 'Understanding diabetes — prevention, monitoring and everyday management, from Life Care Specialty Hospital, Bhatkal.', 'published'),
  (3, 'Is the COVID-19 Vaccine a Dream or Reality?', 'covid-19-vaccine-dream-or-reality', 'Medical Updates', 'Dr. Saad Mohammed Athanikar', '2020-09-25', 'assets/images/gallery/gallery-9.jpg', 'A look at how vaccines are developed and why they became one of our strongest tools against the pandemic.', '<p>When the pandemic began, a safe and effective vaccine felt like a distant hope. Through unprecedented global collaboration, that hope became reality faster than many expected.</p><p>Vaccines work by training the immune system to recognise and fight the virus. Alongside vaccination, everyday precautions continue to keep our community safe.</p><p>Speak to a qualified doctor about which vaccinations are appropriate for you. This article is for general awareness and is not a substitute for professional medical advice.</p>', 'COVID-19 Vaccine — Dream or Reality? | Life Care Bhatkal', 'How COVID-19 vaccines were developed and why they matter — general awareness from Life Care Specialty Hospital.', 'published');

DROP TABLE IF EXISTS `events`;
CREATE TABLE `events` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(240) NOT NULL,
  `slug` VARCHAR(240) NOT NULL,
  `event_date` DATE NULL,
  `cover_image` VARCHAR(255) NULL,
  `description` MEDIUMTEXT NULL,
  `gallery` TEXT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'published',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_slug` (`slug`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `events` (`id`, `title`, `slug`, `event_date`, `cover_image`, `description`, `gallery`, `status`) VALUES
  (1, 'Independence Day Celebration', 'independence-day-celebration', '2023-08-15', 'assets/images/events/event-1.jpg', '<p>The Life Care family came together to celebrate Independence Day with flag hoisting and a warm gathering of our staff and well-wishers.</p>', 'assets/images/events/event-1.jpg|assets/images/events/event-2.jpg|assets/images/events/event-3.jpg|assets/images/events/event-4.jpg', 'published'),
  (2, 'Happy Moments at Life Care', 'happy-moments', '2023-09-30', 'assets/images/events/event-5.jpg', '<p>Moments of joy and gratitude shared by our patients and team — the heart of what we do.</p>', 'assets/images/events/event-5.jpg|assets/images/events/event-6.jpg|assets/images/events/event-7.jpg', 'published'),
  (3, 'Happy Customers', 'happy-customers', '2023-09-15', 'assets/images/events/event-8.jpg', '<p>Grateful patients and families who trusted Life Care with their care.</p>', 'assets/images/events/event-8.jpg|assets/images/events/event-9.jpg', 'published'),
  (4, 'Life at Life Care Specialty Hospital', 'life-at-lifecare', '2023-07-01', 'assets/images/events/event-10.jpg', '<p>A glimpse into daily life, facilities and the team at Life Care Specialty Hospital, Bhatkal.</p>', 'assets/images/events/event-10.jpg|assets/images/events/event-11.jpg|assets/images/events/event-12.jpg', 'published');

DROP TABLE IF EXISTS `gallery_images`;
CREATE TABLE `gallery_images` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `album` VARCHAR(80) NOT NULL DEFAULT 'Facilities',
  `title` VARCHAR(200) NULL,
  `image` VARCHAR(255) NOT NULL,
  `display_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), KEY `idx_album` (`album`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `gallery_images` (`id`, `album`, `title`, `image`, `display_order`) VALUES
  (1, 'Facilities', 'Reception & facilities', 'assets/images/gallery/gallery-1.jpg', 1),
  (2, 'Facilities', 'Hospital interiors', 'assets/images/gallery/gallery-2.jpg', 2),
  (3, 'Facilities', 'Modern equipment', 'assets/images/gallery/gallery-3.jpg', 3),
  (4, 'Facilities', 'Patient care area', 'assets/images/gallery/gallery-4.jpg', 4),
  (5, 'Facilities', 'Hospital building', 'assets/images/gallery/gallery-5.jpg', 5),
  (6, 'Facilities', 'Operation theatre', 'assets/images/gallery/gallery-6.jpg', 6),
  (7, 'Facilities', 'Clinical facilities', 'assets/images/gallery/gallery-7.jpg', 7),
  (8, 'Facilities', 'Laboratory', 'assets/images/gallery/gallery-8.jpg', 8),
  (9, 'Facilities', 'Diagnostics', 'assets/images/gallery/gallery-9.jpg', 9),
  (10, 'Facilities', 'Ultrasound suite', 'assets/images/gallery/gallery-10.jpg', 10),
  (11, 'Events', 'Life Care event photo', 'assets/images/events/event-1.jpg', 11),
  (12, 'Events', 'Life Care event photo', 'assets/images/events/event-2.jpg', 12),
  (13, 'Events', 'Life Care event photo', 'assets/images/events/event-3.jpg', 13),
  (14, 'Events', 'Life Care event photo', 'assets/images/events/event-4.jpg', 14),
  (15, 'Events', 'Life Care event photo', 'assets/images/events/event-5.jpg', 15),
  (16, 'Events', 'Life Care event photo', 'assets/images/events/event-6.jpg', 16),
  (17, 'Events', 'Life Care event photo', 'assets/images/events/event-7.jpg', 17),
  (18, 'Events', 'Life Care event photo', 'assets/images/events/event-8.jpg', 18),
  (19, 'Events', 'Life Care event photo', 'assets/images/events/event-9.jpg', 19),
  (20, 'Events', 'Life Care event photo', 'assets/images/events/event-10.jpg', 20),
  (21, 'Events', 'Life Care event photo', 'assets/images/events/event-11.jpg', 21),
  (22, 'Events', 'Life Care event photo', 'assets/images/events/event-12.jpg', 22);

DROP TABLE IF EXISTS `careers`;
CREATE TABLE `careers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `department` VARCHAR(120) NULL,
  `location` VARCHAR(120) NULL,
  `type` VARCHAR(60) NULL,
  `description` MEDIUMTEXT NULL,
  `requirements` MEDIUMTEXT NULL,
  `apply_email` VARCHAR(160) NULL,
  `display_order` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  PRIMARY KEY (`id`), KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `careers` (`id`, `title`, `department`, `location`, `type`, `description`, `requirements`, `apply_email`, `display_order`, `status`) VALUES
  (1, 'Staff Nurse (GNM / B.Sc Nursing)', 'Nursing', 'Bhatkal', 'Full-time', '<p>Provide compassionate round-the-clock nursing care to in-patients and support clinical teams across departments.</p>', '<ul><li>GNM or B.Sc Nursing qualification</li><li>Valid registration</li><li>Freshers and experienced candidates welcome</li></ul>', 'info@lifecarebhatkal.com', 1, 'active'),
  (2, 'Laboratory Technician (DMLT / BMLT)', 'Laboratory', 'Bhatkal', 'Full-time', '<p>Perform diagnostic laboratory tests accurately and maintain quality standards in our 24×7 hi-tech laboratory.</p>', '<ul><li>DMLT or BMLT qualification</li><li>Attention to detail</li><li>Willingness to work in shifts</li></ul>', 'info@lifecarebhatkal.com', 2, 'active'),
  (3, 'Physiotherapist (BPT / MPT)', 'Physiotherapy', 'Bhatkal', 'Full-time', '<p>Deliver physiotherapy and rehabilitation care in our specialised physiotherapy unit.</p>', '<ul><li>BPT or MPT qualification</li><li>Good communication skills</li></ul>', 'info@lifecarebhatkal.com', 3, 'active'),
  (4, 'Front Desk / Reception Executive', 'Administration', 'Bhatkal', 'Full-time', '<p>Be the welcoming face of Life Care — manage reception, guide patients and coordinate appointments.</p>', '<ul><li>Graduate in any discipline</li><li>Fluent in Kannada, Urdu and English preferred</li><li>Basic computer skills</li></ul>', 'info@lifecarebhatkal.com', 4, 'active');

DROP TABLE IF EXISTS `enquiries`;
CREATE TABLE `enquiries` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(160) NOT NULL,
  `email` VARCHAR(160) NULL,
  `phone` VARCHAR(40) NULL,
  `subject` VARCHAR(200) NULL,
  `department` VARCHAR(160) NULL,
  `message` TEXT NULL,
  `source` VARCHAR(40) NOT NULL DEFAULT 'contact',
  `status` VARCHAR(20) NOT NULL DEFAULT 'new',
  `ip_address` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`), KEY `idx_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
