-- ===================================================================
-- Life Care Specialty Hospital, Bhatkal
-- VISITING DOCTORS import (16 doctors).
-- Loads every visiting super-specialist so they all appear on the
-- website's Visiting Doctors page (which reads live from the DB).
--
-- HOW TO USE (Hostinger): phpMyAdmin -> select your database ->
-- Import tab -> choose this file -> Go.
--
-- This REPLACES the existing visiting doctors with the full, correct
-- set. It does NOT touch OPD/resident or support staff rows.
-- Generated: 2026-09-21 13:09
-- ===================================================================

SET NAMES utf8mb4;

START TRANSACTION;

-- Remove any existing visiting doctors (keeps OPD & support staff intact)
DELETE FROM `doctors` WHERE `doctor_type` = 'visiting';

INSERT INTO `doctors` (`name`, `doctor_type`, `department`, `qualification`, `designation`, `image`, `available_days`, `available_time`, `base_city`, `short_bio`, `full_bio`, `display_order`, `status`) VALUES
  ('Dr. Apoorva N. Acharya', 'visiting', 'General & Laparoscopic Surgery', 'MBBS, MS (Endoscopy & Colonoscopy), DNB', 'Consultant General & Laparoscopic Surgeon', 'assets/images/doctors/dr-apoorva-acharya.png', '1st Thursday of every month', NULL, NULL, 'Consultant General & Laparoscopic Surgeon offering open and minimally invasive surgery for a wide range of abdominal and general surgical conditions, with diagnosis and treatment through endoscopy and colonoscopy.', '<h4>Services Provided</h4><ul><li>Appendicitis</li><li>Gallbladder and Stone Removal</li><li>Hernia Surgery</li><li>Thyroid Tumors and Related Issues</li><li>Breast-related Problems</li><li>Anorectal Problems</li><li>Piles, Fistula, Fissure</li><li>Thyroid Gland Problems</li><li>Spleen-related Problems</li><li>Varicose Veins Surgery</li><li>And other general surgical procedures</li></ul><h4>Conditions Diagnosed &amp; Treated Through Endoscopy and Colonoscopy</h4><ul><li>Gastric problems</li><li>Blood vomiting, Anaemia</li><li>Stomach and intestinal pain</li><li>Diverticulosis</li><li>Abdominal issues</li></ul>', 1, 'published'),
  ('Dr. Arun Shetty Korgi', 'visiting', 'Dermatology & Cosmetology', 'M.B.B.S., DDVL', 'Consultant Dermatologist & Cosmetologist', 'assets/images/doctors/dr-arun-shetty-korgi.png', '2nd & 4th Sunday of every month', NULL, NULL, 'Consultant Dermatologist & Cosmetologist with more than 20 years of experience in medical, surgical and cosmetic skin care.', '<p>More than 20 years of experience.</p><h4>Expertise</h4><ul><li>Acne, Acne Scars (Derma roller / Lasers)</li><li>Chemical Peels</li><li>Sebaceous Cyst &amp; Skin Tags Removal</li><li>Mole Removal Surgery</li><li>Nail Surgery</li><li>Wart Removal</li><li>Electrosurgery</li><li>Radiosurgery (Ablative &amp; Non-Ablative)</li><li>Vitiligo Surgery &amp; Minor Cutaneous Surgery</li></ul>', 2, 'published'),
  ('Dr. Elroy Saldanha', 'visiting', 'Surgical Oncology', 'MS, MCh [RAGES, FMAS, FIAGES, PDCR], PDF Robotic Surgery (Vattikuti Foundation, Michigan, US); Colorectal Surgery training, Cleveland Clinic, Ohio; Thoracic Oncology training, New York Langone Hospital', 'Consultant Surgical Oncologist', 'assets/images/doctors/dr-elroy-saldanha.png', NULL, NULL, NULL, 'Consultant Surgical Oncologist trained in robotic, laparoscopic and minimally invasive cancer surgery, breast oncoplastic procedures and peritoneal surface malignancy (HIPEC & PIPAC) surgeries.', '<p>Fr. Muller Medical College Hospital, Mangalore.</p><p>Trained in Robotic, Laparoscopic Minimal Invasive Surgery, Breast Oncoplastic Procedures and Peritoneal Surface Malignancy HIPEC &amp; PIPAC Surgeries.</p><h4>Specialist In</h4><ul><li>Breast Conservative Surgeries &amp; Sentinel Lymph Node Biopsy</li><li>Head &amp; Neck Cancer with Oral, Salivary Gland Cancer</li><li>Scarless Thyroidectomy; Gastrointestinal surgeries - Esophagus, Stomach</li><li>Colon &amp; Rectal Cancer; HPB surgeries - Liver, Biliary &amp; Pancreatic Cancer</li><li>Gynecological surgeries - Ovarian, Uterine &amp; Cervical Cancer</li><li>Bone &amp; Soft Tissue Sarcoma, Limb Salvage Surgery</li><li>Chemoport insertions</li><li>Varicose vein surgery</li><li>Breast surgery</li><li>Thyroid surgery</li></ul><h4>Special Packages @ Life Care</h4><ul><li>Appendectomy (Appendix)</li><li>Hernia</li><li>Hydrocele</li><li>Swelling excisions like lipoma / lymph node excision</li><li>Gall bladder surgery</li><li>Hysterectomy Surgery</li></ul><p><strong>Note:</strong> Book appointments for all general and onco surgery cases.</p>', 3, 'published'),
  ('Dr. Gaurav B. Shetty', 'visiting', 'Plastic & Reconstructive Surgery', NULL, 'Reconstructive Plastic Surgeon', 'assets/images/doctors/dr-gaurav-b-shetty.png', NULL, NULL, NULL, 'Reconstructive Plastic Surgeon focusing on trauma and post-accident reconstruction, burn care, congenital anomaly correction, hand surgery and post-cancer reconstruction.', '<h4>Reconstructive Plastic Surgery</h4><ul><li>Trauma &amp; Post-Accident Reconstruction</li><li>Burn Care &amp; Scar Revision</li><li>Congenital Anomaly Correction</li><li>Hand Surgery &amp; Nerve Repair</li><li>Post-Cancer Reconstruction</li></ul>', 4, 'published'),
  ('Dr. Prajwal K Rao', 'visiting', 'Plastic & Aesthetic Surgery', NULL, 'Aesthetic Plastic Surgeon', 'assets/images/doctors/dr-prajwal-k-rao.png', NULL, NULL, NULL, 'Aesthetic Plastic Surgeon offering a full range of cosmetic and body-contouring procedures.', '<h4>Aesthetic Plastic Surgery</h4><ul><li>Laser For Varicose Veins</li><li>Gynecomastia Surgery</li><li>Liposuction &amp; Body Contouring</li><li>Tummy Tuck / Mommy Makeover</li><li>Rhinoplasty &amp; Facial Aesthetics</li><li>Breast Augmentation / Reduction</li><li>Hair Transplant</li></ul>', 5, 'published'),
  ('Dr. Shruthi A G', 'visiting', 'Cosmetic Gynaecology', NULL, 'Reproductive Medicine and Cosmetic Gynaecologist', 'assets/images/doctors/dr-shruthi-a-g.png', NULL, NULL, NULL, 'Specialist in Reproductive Medicine and Cosmetic Gynaecology, offering intimate wellness and aesthetic gynaecology procedures.', '<h4>Cosmetic Gynecology</h4><ul><li>Vaginal Tightening (Laser / Surgical)</li><li>Labiaplasty</li><li>Non-Surgical Intimate Rejuvenation</li><li>Hymenoplasty</li><li>Post-Delivery Aesthetic Concerns</li><li>PRP for Intimate Health</li></ul>', 6, 'published'),
  ('Dr. Himamshu Acharya', 'visiting', 'Endocrinology', 'MBBS, MD (Medicine), DM (Endocrinology)', 'Consultant Endocrinologist (Hormone Specialist)', 'assets/images/doctors/dr-himamshu-acharya.png', '1st Thursday of every month', NULL, NULL, 'Consultant Endocrinologist (Hormone Specialist) providing expert diagnosis and personalized treatment for hormonal and metabolic disorders.', '<p>Expert diagnosis and personalized treatment from a trusted Endocrinologist.</p><h4>Consult if you are struggling with</h4><ul><li>Diabetes or thyroid disorders</li><li>Hormonal imbalance or obesity</li><li>PCOD / PCOS or infertility issues</li><li>Growth or puberty-related problems</li><li>Osteoporosis or adrenal problems</li><li>Pituitary disorders</li></ul>', 7, 'published'),
  ('Dr. Mahima Acharya', 'visiting', 'Psychiatry', 'MBBS, MD (Psychiatry) - From Manipal', 'Consultant Neuro Psychiatrist', 'assets/images/doctors/dr-mahima-acharya.png', '4th Thursday of every month', NULL, NULL, 'Consultant Neuro Psychiatrist with 14 years of experience, specialising in women and child mental health, de-addiction treatment and psychosomatic medicine.', '<p>14 years of work experience in psychiatry.</p><h4>Areas of Focus</h4><ul><li>Specialized in Women &amp; Child Mental Health</li><li>De-addiction treatment</li><li>Psychosomatic Medicine</li><li>Depression</li><li>Anxiety</li><li>Panic disorder</li><li>Sexual dysfunction</li><li>Counseling services also available</li></ul>', 8, 'published'),
  ('Dr. Narasimha Pai', 'visiting', 'Cardiology', 'MBBS, MD, DM (Cardiology), DNB Cardiac, FICC, FACC, FESC', 'Consultant Cardiology', 'assets/images/doctors/dr-narasimha-pai.png', '1st Sunday of every month', NULL, NULL, 'Consultant Cardiologist from Mangalore (KMC) caring for all heart-related ailments.', '<p>Renowned Cardiologist from Mangalore - KMC.</p><h4>Expertise - All Heart Related Ailments</h4><ul><li>Heart failure</li><li>Coronary Artery Disease</li><li>Atherosclerosis</li><li>Hypertension</li><li>Myocardial Infarction</li><li>Echo Cardiography Test</li></ul>', 9, 'published'),
  ('Dr. Raghavendra B S', 'visiting', 'Neurology', 'MBBS, MD (Medicine), DM Neurology', 'Consultant Neurologist', 'assets/images/doctors/dr-raghavendra-b-s.png', '4th Saturday of every month', NULL, NULL, 'Consultant Neurologist, Professor and HOD of Neurology at Father Muller Medical College.', '<p>Professor and HOD Neurology, Father Mullers Medical College.</p><h4>Specialist In</h4><ul><li>Headache</li><li>Neuropathy</li><li>Epilepsy (fits)</li><li>Stroke</li></ul><h4>Services</h4><ul><li>Nerve Conduction Study</li><li>EEG</li></ul>', 10, 'published'),
  ('Dr. Rajesh P. Nair', 'visiting', 'Neurosurgery', 'MS, M.Ch (Neurosurgery), DNB, MNAMS, FAGE, FRSM, IFAANS', 'Senior Consultant Neurosurgeon', 'assets/images/doctors/dr-rajesh-p-nair.png', '1st & 3rd Saturday of every month', NULL, NULL, 'Senior Consultant Neurosurgeon managing brain, spine and complex neurosurgical conditions using minimally invasive and advanced techniques.', '<h4>Surgeries Including</h4><ul><li>TBI (Head Injury), Vascular and Skull Base Pathology</li><li>DBS (Brain Pacemaker), MIS Fixation (Keyhole Surgery), Complex Spine Fractures</li><li>MIS-TLIF, ALIF, XLIF - Spine Fusion / Spine Surgery</li><li>CSF Diversion, ETV (Surgery for Brain Fluid)</li><li>CVJ (Head &amp; Neck Surgery) &amp; Posterior Fossa Anomalies</li><li>Paediatric &amp; Adult Neuro-Oncology, SICH (Bleeding in Brain), Aneurysm Clipping, Stroke, Epilepsy Surgery</li></ul>', 11, 'published'),
  ('Dr. Shravan R Shanbhag', 'visiting', 'Urology', 'MBBS, MS (General Surgery), DNB (Urology), Diploma in Laparoscopy', 'Consultant Urologist', 'assets/images/doctors/dr-shravan-r-shanbhag.png', NULL, NULL, NULL, 'Consultant Urologist with more than 15 years of surgical experience and super-specialty training in Urology.', '<p>More than 15 years experience in the surgical field.</p><p>Completed MBBS, MS from Rajiv Gandhi University of Health Sciences, Bangalore. Super specialty in Urology from Medical Trust Hospital, Kochi.</p><h4>Services Offered</h4><ul><li>Lithotripsy (Urinary tract stone management)</li><li>Prostate disease (Medical &amp; Surgical management)</li><li>Laser surgical procedures</li><li>Urinary Tract Infections (UTI) management</li><li>Andrology (Erectile Dysfunction &amp; Male Infertility)</li><li>Uro-oncology (Cancers of Genitourinary tract)</li><li>Paediatric urology</li><li>Laparoscopic surgeries (Key hole surgeries)</li><li>Reconstructive urology (urethral stricture diseases)</li><li>Kidney transplantation</li><li>Neuro-urology</li></ul>', 12, 'published'),
  ('Dr. Suhas G. C', 'visiting', 'Interventional Cardiology', 'MBBS, MD, DM (Cardiology)', 'Consultant Interventional Cardiologist', 'assets/images/doctors/dr-suhas-g-c.png', '1st & 3rd Tuesday of every month', NULL, NULL, 'Consultant Interventional Cardiologist trained in CTO PCI, CHIP PCI and complex coronary interventions.', '<p>Trained in CTO PCI, CHIP PCI and Complex Coronary Interventions.</p><h4>Specialises In</h4><ul><li>Complex Coronary and Peripheral Angioplasty</li><li>Complex Interventions</li><li>Pacemaker &amp; ICD Implantation</li><li>Arrhythmia and Heart Failure Management</li></ul>', 13, 'published'),
  ('Dr. Mohammad Yasin Soudagar', 'visiting', 'Dental & Maxillofacial Surgery', 'BDS, MDS, FAM (Germany)', 'Consultant Oral & Maxillofacial Surgeon (Dental)', 'assets/images/doctors/dr-mohammad-yasin-soudagar.png', NULL, NULL, NULL, 'Consultant Oral & Maxillofacial Surgeon (Dental) handling dental surgery, facial trauma, implants and aesthetic facial procedures.', '<h4>Expertise</h4><ul><li>Impacted Tooth</li><li>Odontogenic Cyst</li><li>Dental Implants</li><li>Maxillofacial Trauma</li><li>Orthognathic Surgery</li><li>Gummy Smile Correction</li><li>Oral Cancer</li><li>Cleft Lip &amp; Palate</li><li>Hair Transplant</li><li>Botox &amp; Fillers</li><li>Lip Filler</li><li>Scar Revision</li><li>Mole Removal</li><li>Wart Removal</li></ul><p><strong>Note:</strong> Book appointments for all Dental Surgery Cases.</p>', 14, 'published'),
  ('Dr. Garry V Pais', 'visiting', 'Cardiology', 'MBBS, MD, DNB (Cardiology)', 'Consultant Cardiologist', 'assets/images/doctors/dr-garry-v-pais.png', NULL, NULL, NULL, 'Consultant Cardiologist featured in the Mega Cardiac Health Checkup at Life Care Specialty Hospital.', '<p>Featured in the Mega Cardiac Health Checkup (Life Care Specialty Hospital in association with Srinivas Hospital).</p><h4>Mega Cardiac Health Checkup - Package Rs. 1500 includes</h4><ul><li>Vitals, BP, Temperature &amp; SpO2</li><li>ECG</li><li>ECHO</li><li>Lipid Profile + Blood Test</li><li>Consultation</li></ul><h4>Recommended For</h4><ul><li>People with BP, diabetes, chest discomfort, breathlessness, obesity, smoking, stress, or family history</li></ul>', 15, 'published'),
  ('Dr. Nihal Ali Kumble', 'visiting', 'Gastroenterology & Hepatology', 'MBBS, MD (Internal Medicine), DrNB (Gastroenterology & Hepatology)', 'Consultant Gastroenterologist and Hepatologist', 'assets/images/doctors/dr-nihal-ali-kumble.png', '3rd Saturday of every month', '2:00 PM to 4:00 PM', NULL, 'Consultant Gastroenterologist and Hepatologist expert in advanced GI and liver care, including advanced GI endoscopy, ERCP and therapeutic endoscopy.', '<p>Expert in Advanced GI &amp; Liver Care. Specializing in Advanced GI Endoscopy, ERCP, and Therapeutic Endoscopy - comprehensive care for a wide range of gastrointestinal and liver disorders with precision and expertise.</p><h4>Approach</h4><ul><li>Early Detection &amp; Prevention</li><li>Minimally Invasive Procedures</li><li>Evidence-Based Treatment</li><li>Personalized Patient Care</li></ul><h4>Areas of Expertise</h4><ul><li>Advanced GI Endoscopy &amp; Therapeutic Procedures</li><li>ERCP (Endoscopic Retrograde Cholangiopancreatography)</li><li>Screening &amp; Management of Hepatitis (A, B, C, E)</li><li>Management of Hepatocellular Carcinoma (HCC)</li><li>Treatment of Fatty Liver / Steatotic Liver Disease</li><li>Pre-Transplant Liver Evaluation &amp; Care</li></ul>', 16, 'published');

COMMIT;
