<?php
/**
 * SQL schema + seed generator.
 * Reads includes/seed_data.php (single source of truth) and writes
 * database/schema.sql — the file you import in Hostinger phpMyAdmin.
 *
 * Run locally:  php tools/build_sql.php
 * Re-run whenever seed_data.php changes so the DB import stays in sync.
 */
declare(strict_types=1);

define('ROOT_PATH', dirname(__DIR__));
$seed = require ROOT_PATH . '/includes/seed_data.php';

/* ---- helpers -------------------------------------------------------- */
$OUT = "-- ===================================================================\n"
     . "-- Life Care Specialty Hospital, Bhatkal — Database Schema + Seed Data\n"
     . "-- GENERATED by tools/build_sql.php from includes/seed_data.php.\n"
     . "-- Do not edit by hand — edit seed_data.php and re-run the generator.\n"
     . "-- Import: phpMyAdmin → your database → Import → choose this file.\n"
     . "-- Generated: " . date('Y-m-d H:i') . "\n"
     . "-- ===================================================================\n\n"
     . "SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS = 0;\nSET time_zone = '+05:30';\n\n";

/** Quote a value for SQL (NULL / int / string). */
function v($val): string {
    if ($val === null) return 'NULL';
    if (is_int($val))  return (string)$val;
    if (is_bool($val)) return $val ? '1' : '0';
    return "'" . str_replace(["\\", "'"], ["\\\\", "\\'"], (string)$val) . "'";
}
/** Build a multi-row INSERT for $rows using $cols (keys). */
function insert(string $table, array $cols, array $rows): string {
    if (!$rows) return "-- (no rows for $table)\n\n";
    $sql = "INSERT INTO `$table` (`" . implode('`, `', $cols) . "`) VALUES\n";
    $lines = [];
    foreach ($rows as $r) {
        $vals = array_map(fn($c) => v($r[$c] ?? null), $cols);
        $lines[] = '  (' . implode(', ', $vals) . ')';
    }
    return $sql . implode(",\n", $lines) . ";\n\n";
}
function drop_create(string $table, string $body): string {
    return "DROP TABLE IF EXISTS `$table`;\nCREATE TABLE `$table` (\n$body\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n\n";
}

/* ==================================================================== admins */
$OUT .= drop_create('admins', <<<SQL
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL,
  `email` VARCHAR(160) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `name` VARCHAR(120) NOT NULL DEFAULT '',
  `role` VARCHAR(30) NOT NULL DEFAULT 'admin',
  `failed_attempts` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `locked_until` DATETIME NULL DEFAULT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_username` (`username`)
SQL);
// Two accounts — CHANGE THESE PASSWORDS after first login!
//  • admin    → agency account, full access to every section.
//  • hospital → hospital staff account, limited to Dashboard, Doctors,
//               Blog Posts, Enquiries and Site Settings (see admin/includes/auth.php).
$defaultPass    = 'lifecare@admin';
$hospitalPass   = 'lifecare@hospital';
$OUT .= insert('admins', ['username','email','password_hash','name','role'], [
  [
    'username'=>'admin','email'=>$seed['settings']['email'],
    'password_hash'=>password_hash($defaultPass, PASSWORD_DEFAULT),
    'name'=>'Agency Administrator','role'=>'admin',
  ],
  [
    'username'=>'hospital','email'=>$seed['settings']['email'],
    'password_hash'=>password_hash($hospitalPass, PASSWORD_DEFAULT),
    'name'=>'Hospital Administrator','role'=>'hospital',
  ],
]);
$OUT .= "-- Agency login   → username: admin     |  password: {$defaultPass}   (full access)\n"
      . "-- Hospital login → username: hospital  |  password: {$hospitalPass}  (limited access)\n"
      . "-- IMPORTANT: log in and change both passwords immediately.\n\n";

/* ==================================================================== site_settings */
$OUT .= drop_create('site_settings', <<<SQL
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `setting_key` VARCHAR(80) NOT NULL,
  `setting_value` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_key` (`setting_key`)
SQL);
$settingsRows = [];
foreach ($seed['settings'] as $k => $val) $settingsRows[] = ['setting_key'=>$k,'setting_value'=>$val];
$OUT .= insert('site_settings', ['setting_key','setting_value'], $settingsRows);

/* ==================================================================== departments */
$OUT .= drop_create('departments', <<<SQL
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(160) NOT NULL,
  `slug` VARCHAR(160) NOT NULL,
  `category` VARCHAR(20) NOT NULL DEFAULT 'opd',
  `thumb_image` VARCHAR(255) NULL,
  `hero_image` VARCHAR(255) NULL,
  `short_desc` TEXT NULL,
  `overview` MEDIUMTEXT NULL,
  `services` TEXT NULL,
  `seo_title` VARCHAR(200) NULL,
  `meta_description` VARCHAR(300) NULL,
  `display_order` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'published',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_slug` (`slug`),
  KEY `idx_cat` (`category`), KEY `idx_status` (`status`)
SQL);
$OUT .= insert('departments',
    ['id','name','slug','category','thumb_image','hero_image','short_desc','overview','services','seo_title','meta_description','display_order','status'],
    $seed['departments']);

/* ==================================================================== doctors */
$OUT .= drop_create('doctors', <<<SQL
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(160) NOT NULL,
  `doctor_type` VARCHAR(20) NOT NULL DEFAULT 'resident',
  `department` VARCHAR(160) NULL,
  `qualification` VARCHAR(200) NULL,
  `designation` VARCHAR(200) NULL,
  `image` VARCHAR(255) NULL,
  `available_days` VARCHAR(120) NULL,
  `available_time` VARCHAR(160) NULL,
  `base_city` VARCHAR(200) NULL,
  `short_bio` TEXT NULL,
  `full_bio` MEDIUMTEXT NULL,
  `display_order` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'published',
  PRIMARY KEY (`id`),
  KEY `idx_type` (`doctor_type`), KEY `idx_status` (`status`)
SQL);
$OUT .= insert('doctors',
    ['id','name','doctor_type','department','qualification','designation','image','available_days','available_time','base_city','short_bio','full_bio','display_order','status'],
    $seed['doctors']);

/* ==================================================================== testimonials */
$OUT .= drop_create('testimonials', <<<SQL
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `location` VARCHAR(120) NULL,
  `quote` TEXT NOT NULL,
  `rating` TINYINT NOT NULL DEFAULT 5,
  `display_order` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'published',
  PRIMARY KEY (`id`), KEY `idx_status` (`status`)
SQL);
$OUT .= insert('testimonials', ['id','name','location','quote','rating','display_order','status'], $seed['testimonials']);

/* ==================================================================== faqs */
$OUT .= drop_create('faqs', <<<SQL
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(300) NOT NULL,
  `answer` TEXT NOT NULL,
  `display_order` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'published',
  PRIMARY KEY (`id`), KEY `idx_status` (`status`)
SQL);
$OUT .= insert('faqs', ['id','question','answer','display_order','status'], $seed['faqs']);

/* ==================================================================== blog_posts */
$OUT .= drop_create('blog_posts', <<<SQL
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(240) NOT NULL,
  `slug` VARCHAR(240) NOT NULL,
  `category` VARCHAR(80) NULL,
  `author` VARCHAR(160) NULL,
  `publish_date` DATE NULL,
  `featured_image` VARCHAR(255) NULL,
  `excerpt` TEXT NULL,
  `content` MEDIUMTEXT NULL,
  `seo_title` VARCHAR(240) NULL,
  `meta_description` VARCHAR(300) NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'published',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_slug` (`slug`),
  KEY `idx_status` (`status`), KEY `idx_date` (`publish_date`)
SQL);
$OUT .= insert('blog_posts',
    ['id','title','slug','category','author','publish_date','featured_image','excerpt','content','seo_title','meta_description','status'],
    $seed['posts']);

/* ==================================================================== events */
$OUT .= drop_create('events', <<<SQL
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(240) NOT NULL,
  `slug` VARCHAR(240) NOT NULL,
  `event_date` DATE NULL,
  `cover_image` VARCHAR(255) NULL,
  `description` MEDIUMTEXT NULL,
  `gallery` TEXT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'published',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_slug` (`slug`),
  KEY `idx_status` (`status`)
SQL);
$OUT .= insert('events', ['id','title','slug','event_date','cover_image','description','gallery','status'], $seed['events']);

/* ==================================================================== gallery_images */
$OUT .= drop_create('gallery_images', <<<SQL
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `album` VARCHAR(80) NOT NULL DEFAULT 'Facilities',
  `title` VARCHAR(200) NULL,
  `image` VARCHAR(255) NOT NULL,
  `display_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), KEY `idx_album` (`album`)
SQL);
$OUT .= insert('gallery_images', ['id','album','title','image','display_order'], $seed['gallery']);

/* ==================================================================== careers */
$OUT .= drop_create('careers', <<<SQL
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `department` VARCHAR(120) NULL,
  `location` VARCHAR(120) NULL,
  `type` VARCHAR(60) NULL,
  `description` MEDIUMTEXT NULL,
  `requirements` MEDIUMTEXT NULL,
  `apply_email` VARCHAR(160) NULL,
  `display_order` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  PRIMARY KEY (`id`), KEY `idx_status` (`status`)
SQL);
$OUT .= insert('careers',
    ['id','title','department','location','type','description','requirements','apply_email','display_order','status'],
    $seed['careers']);

/* ==================================================================== enquiries (empty; filled by contact form) */
$OUT .= drop_create('enquiries', <<<SQL
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(160) NOT NULL,
  `email` VARCHAR(160) NULL,
  `phone` VARCHAR(40) NULL,
  `subject` VARCHAR(200) NULL,
  `department` VARCHAR(160) NULL,
  `message` TEXT NULL,
  `source` VARCHAR(40) NOT NULL DEFAULT 'contact',
  `status` VARCHAR(20) NOT NULL DEFAULT 'new',
  `ip_address` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`), KEY `idx_created` (`created_at`)
SQL);

$OUT .= "SET FOREIGN_KEY_CHECKS = 1;\n";

/* ---- write ---------------------------------------------------------- */
$dir = ROOT_PATH . '/database';
if (!is_dir($dir)) mkdir($dir, 0755, true);
$path = $dir . '/schema.sql';
file_put_contents($path, $OUT);
echo "Wrote " . strlen($OUT) . " bytes → database/schema.sql\n";
